---
title: "Friendship Network Analysis"
author: "Dharma Tega Bhattu and Collin Stratton"
date: "2-27-2022"
output: html_notebook
---

# Introduction

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Setup

```{r set_libs}
library(igraph)
library(GGally)
library(sna)
library(ergm)
```

### netlm

```{r netlm}
set.seed(123)
filepath <- "/Users/collinstratton/Google Drive/School/GCU/Fall 2021 - Spring 2022/CST-440/CST-440/FriendshipNetworkAnalysis/CST-440-RS-FriendshipNetworkMatrix.csv"
friendmatrix <- read.csv(filepath, header=TRUE, row.names=1, check.names=FALSE, na.strings="")

matrix <- as.matrix(friendmatrix)
g <- graph.adjacency(matrix, mode="undirected", weighted=TRUE)

plot(g)
```

```{r}
cmatrix <- sapply(matrix, as.character)

# function to get the first and second character of each node
relationship <- function(matrix, x, y) {
  if (matrix[x, y] == "0") {
    return(c(0, 0))
  } else {
    pos <- x * y
    attitude <- substr(cmatrix[pos], 1, 1)
    degree <- substr(cmatrix[pos], 2, 2)
    return(c(as.numeric(attitude), as.numeric(degree)))
  }
}
```

```{r}
# create two 20x20 matrices
matrix1 <- matrix(0, nrow=20, ncol=20)
matrix2 <- matrix(0, nrow=20, ncol=20)

# fill the matrices with the values from the relationship function
for (i in 1:20) {
  for (j in 1:20) {
    matrix1[i, j] <- as.numeric(relationship(matrix, i, j)[1])
    matrix2[i, j] <- as.numeric(relationship(matrix, i, j)[2])
  }
}
# replace na with 0
matrix1[is.na(matrix1)] <- 0
matrix2[is.na(matrix2)] <- 0

matrix1
matrix2
```

```{r}
nl<-netlm(matrix2, matrix1,reps=250)
nl
summary(nl)
```

```{r ergm}
e <- ergm(matrix1 ~ edges)

print(summary(e))
```